### ISSUE TITLE
utf-8 encoding issue on data.txt

### ISSUE THREAD

**Issue by lucas0** [wjko2/Domain-Agnostic-Sentence-Specificity-Prediction#5]
```
Traceback (most recent call last):
  File "test.py", line 159, in <module>
    train,valid, test,unlab ,trainu= get_pdtb(params.nlipath,params.dom,params.test_data,params.tv)
  File "/home/lucas/Lux/res/specificity/Domain-Agnostic-Sentence-Specificity-Prediction/data2.py", line 133, in get_pdtb
    s1['train']['sent'] = [line.rstrip() for line in open(s1['train']['path'], 'r')]
  File "/home/lucas/Lux/res/specificity/Domain-Agnostic-Sentence-Specificity-Prediction/data2.py", line 133, in <listcomp>
    s1['train']['sent'] = [line.rstrip() for line in open(s1['train']['path'], 'r')]
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3164: ordinal not in range(128)
```

because in dataset/data/data.txt line 3534:

Some clichés, it seems, are truly universal.

'é' can't be decoded as ascii. 

this error can be "fixed" by changing:

`s1['train']['sent'] = [line.rstrip() for line in open(s1['train']['path'], 'r')]`

for

`s1['train']['sent'] = [line.decode('ascii', "ignore").rstrip() for line in open(s1['unlab']['path'], 'r')]`

in data2.py.

**Comment by lucas0** [comment]
Other places have the same problem. You should be reading files with "rb" and decoding accordingly.
